# Generated by Django 3.2.5 on 2021-07-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qushish', models.IntegerField()),
                ('kupay', models.IntegerField()),
                ('bulish', models.IntegerField()),
                ('ayirish', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bajarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son1', models.IntegerField()),
                ('son2', models.IntegerField()),
                ('natija', models.IntegerField()),
                ('shart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hisob_app.shart')),
            ],
        ),
    ]
