# Generated by Django 3.2.5 on 2021-07-05 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hisob_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shart',
            name='ayirish',
        ),
        migrations.RemoveField(
            model_name='shart',
            name='bulish',
        ),
        migrations.RemoveField(
            model_name='shart',
            name='kupay',
        ),
        migrations.RemoveField(
            model_name='shart',
            name='qushish',
        ),
        migrations.AddField(
            model_name='shart',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bajarish',
            name='shart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hisob_app.shart'),
        ),
    ]
