# Generated by Django 3.2.5 on 2021-07-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hisob_app', '0002_auto_20210705_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajarish',
            old_name='natija',
            new_name='number1',
        ),
        migrations.RenameField(
            model_name='bajarish',
            old_name='son1',
            new_name='number2',
        ),
        migrations.RenameField(
            model_name='bajarish',
            old_name='son2',
            new_name='result',
        ),
    ]
